config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#top'
  get 'home/about'

  get '/search', to: 'searches#search'

  resources :books, only: [:create, :show, :index, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :create, :show, :edit, :update, :index] do
      resource :relationships, only: [:create, :destroy, ]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  #コメント機能
  has_many :post_comments, dependent: :destroy
  #いいね機能
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  #投稿数
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) } #今日
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) } #昨日

  scope :created_this_week, -> {where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day)} #今週
  scope :created_last_week, -> {where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day)} #前週


  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorites, source: :book

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end

  attachment :image
  attachment :profile_image

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_user!,exept: [:top]

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    user_path(@user.id)
  end

  def after_sign_up_path_for(resource)
    user_path(@user.id)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!

  def index
    @books = Book.page(params[:page]).reverse_order
    @book = Book.new
    @user = current_user
    @books = Book.includes(:favorited_users).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.page(params[:page]).reverse_order
      @user = current_user
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @post_comment = PostComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end


  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :image)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    @book = book
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    @book = book
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.post_comments.new(post_comment_params)
    @comment.book_id = @book.id
    @comment.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    @comment = PostComment.find_by(id: params[:id], book_id: params[:book_id])
    @comment.destroy
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    current_user.follow(params[:user_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_back(fallback_location: root_path)
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @model = params["model"]
    @content = params["content"]
    @method = params["method"]
    @records = search_for(@model, @content, @method)
    @user = current_user
  end

  private
  def search_for(model, content, method)
    if model == 'user'
      if method == 'perfect'
        User.where(name: content)
      else
        User.where('name LIKE ?', '%'+content+'%')
      end
    elsif model == 'book'
      if method == 'perfect'
        Book.where(title: content)
      else
        Book.where('title LIKE ?', '%'+content+'%')
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
    #投稿数
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end

  def index
    @books = Book.new
    @users = User.all
    @user = current_user

  end

  def create
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "user info was updated successfully"
      redirect_to user_path(@user.id)
    else
      render :edit
    end

  end

  def user_params
    params.require(:user).permit(:name, :image, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<tbody>
 <% books.each do |book| %>
 <tr>
  <td>
   <%= link_to user_path(book.user.id) do %>
    <%= attachment_image_tag book.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
   <% end %>
  </td>
  <td><%= link_to book.title, book_path(book.id) %></td>
  <td><%= book.body %></td>
  <td class="favorite-btn<%= book.id %>">
   <%= render "favorites/favorite-btn", book: book %>
  </td>
  <td>コメント数：<%= book.post_comments.count %></td>
 </tr>
 <% end %>

app/views/books/_index.html.erb
<main>
  <p id="notice"></p>
  <div class='container px-3 px-sm-0'>
   <div class='row'>
     <table class='table'>
        <thead>
            <tr>
                <th></th>
                <th>Title</th>
                <th>Body</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody id="post">
        <% books.each do |book| %>
          <tr>
            <td>
             <%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
             <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
        </tbody>
     </table>
   </div>
  </div>
</main>

app/views/books/_list.html.erb
<div class='col-md-3'>
      <h2>User info</h2>
      <table class='table'>
        <tr><%= attachment_image_tag user, :profile_image, size: "100x100", format: 'jpeg', fallback: "no_image.jpg" %></tr>
         <th>name</th>
         <th><%= user.name %></th>
        </tr>
        <tr>
         <th>introduction</th>
         <th><%= user.introduction %></th>
         <tr>
          <th>follows</th>
          <th>
           <%= link_to user_followings_url(user.id) do %>
             <%= user.followings.count %>
           <% end %>
          </th>
         </tr>
         <tr>
          <th>followers</th>
          <th>
           <%= link_to user_followers_url(user.id) do %>
            <%= user.followers.count %>
           <% end %>
          </th>
         </tr>
         <tr>
          <% if user.id != current_user.id %>
            <td><%= render "relationships/button", user: user %></td>
          <% end %>
         </tr>
        </tr>
      </table>
      <div class='row'>
       <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
         <i class="fas fa-user-cog"></i>
       <% end %>
      </div>
      <h1>New book</h1>
      <%= form_with model:book, url:'/books', local:true do |f| %>
      <div class="form-group">
       <label for='book_title'>Title</label>
       <input class="form-control book_title" type="text" name="book[title]" id="book_title" />
      </div>
      <div class="form-group">
       <label for="book_opinion">Opinion</label>
       <textarea class="form-control book_body" name="book[body]" id="book_body"></textarea>
      </div>
      <div class="form-group">
       <input type="submit" name"commit" value="Create Book" class="btn btn-success" data-disable="Create Book" />
      </div>
      <% end %>
</div>

app/views/books/edit.html.erb
<main>
  <p id="notice"></p>
  <div class='container'>
    <div class='row'>
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
          <div id="error_explination">
          <% if @book.errors.any? %>
            <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
            <% @book.errors.full_messages.each do |message| %>
              <ul>
               <li><%= message %></li>
              </ul>
            <% end %>
          <% end %>
          </div>
        <%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title, class:"form-control" %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class:"form-control" %>
          </div>
          <div class="form-group">
            <input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book" />
          </div>
        <% end %>
        <%= link_to "Show", book_path(@book.id) %> |
        <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <p id="notice"></p>
  <div class='container px-5 px-sm-0'>
   <div id="error_explination">
    <% if @book.errors.any? %>
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
      <% @book.errors.full_messages.each do |message| %>
        <ul>
         <li><%= message %></li>
        </ul>
      <% end %>
    <% end %>
   </div>
   <%= render 'searches/form' %>
   <div class='row'>
    <%= render 'books/list', book: @books, user: @user %>
    <div class='col-md-8 offset-md-1'>
     <h2>Books</h2>
     <table class="table table-hover table-inverse">
      <thead>
       <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
       </tr>
      </thead>
      <tbody>
       <%= render 'books/book', books: @books, user: @user %>
      </tbody>
     </table>
    </div>
   </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
  <p id="notice"></p>
  <div class='container px-5 px-sm-0'>
   <div class='row'>
    <%= render 'books/list', book: @books, user: @user %>
     <div class='col-md-8 offset-md-1'>
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
       <tbody>
        <tr>
         <td>
          <%= link_to user_path(@book.user.id) do %>
            <%= attachment_image_tag @book.user, :image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %><br>
            <%= @user.name %>
          <% end %>
         </td>
         <td><%= link_to @book.title, book_path(@book.id) %></td>
         <td><%= @book.body %></td>
         <td class="favorite-btn<%= @book.id %>">
          <%= render "favorites/favorite-btn", book: @book %>
         </td>
         <td>コメント数：<%= @book.post_comments.count %></td>
         <% if @user.id == current_user.id %>
         <td><%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-sm btn-success" %></td>
         <td>
          <%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？", class:"btn btn-sm btn-danger" %>
         </td>
         <% end %>
        </tr>
       </tbody>
      </table>
      <table class= "commentsArea">
       <div>
        <%= render "post_comments/comment", book: @book %>
       </div>
      </table>
       <tr>
         <%= form_with(model: [@book, @post_comment] ) do |f| %>
         <td><%= f.text_area :comment, size: "90x5", class: "inputComment" %><br>
          <%= f.submit "送信" %>
         <% end %>
         </td>
       </tr>
     </div>
   </div>
  </div>
</main>

app/views/favorites/_favorite-btn.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    ♥<%= book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    ♡<%= book.favorites.count %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$(".favorite-btn<%= @book.id %>").html("<%= escape_javascript(render partial: 'favorites/favorite-btn', locals: {book: @book}) %>");

app/views/favorites/destroy.js.erb
$(".favorite-btn<%= @book.id %>").html("<%= escape_javascript(render partial: 'favorites/favorite-btn', locals: {book: @book}) %>");

app/views/home/about.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">
        Welcome to
        <i class="fas fa-book"></i><strong>Bookers</strong>
      </h1>
    </div>
  </div>
</main>

app/views/home/top.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/post_comments/_comment.html.erb
<% book.post_comments.each do |post_comment| %>
<tr>
  <td>
   <%= link_to user_path(post_comment.user.id) do %>
     <%= attachment_image_tag post_comment.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %><br>
     <%= post_comment.user.name %>
   <% end %>
  </td>
  <td>
   <%= post_comment.comment %>
  </td>
  <% if post_comment.user == current_user %>
   <td>
    <%= link_to "Destroy", book_post_comment_path(post_comment.book, post_comment), method: :delete, remote: true, cla %>
   </td>
  <% end %>
</tr>
<% end %>

app/views/post_comments/create.js.erb
$(".commentsArea").html("<%= j(render 'post_comments/comment', post_comments: @comment.book.post_comments, book: @book ) %>")
$(".inputComment").val('');

app/views/post_comments/destroy.js.erb
$(".commentsArea").html("<%= j(render 'post_comments/comment', post_comments: @comment.book.post_comments, book: @book ) %>");

app/views/relationships/_button.html.erb
<% if current_user.following?(user) %>
  <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, remote: true, class:"bg-info text-light btn btn-outline-secondary btn-block" %>
<% else %>
  <%= link_to "フォローする", user_relationships_path(user.id), method: :post, remote: true, class:"bg-success text-light btn btn-outline-secondary btn-block" %>
<% end %>

app/views/relationships/create.js.erb
$("#button<%= @user.id %>").html("<%= j(render partial: 'relationships/button', locals: {user: @user}) %>");

app/views/relationships/destroy.js.erb
$("#button<%= @user.id %>").html("<%= j(render partial: 'relationships/button', locals: {user: @user}) %>");

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
<main>
  <p id="notice"></p>
  <div class='container px-3 px-sm-0'>
   <div class='row'>
     <table class='table'>
      <thead>
       <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
       </tr>
      </thead>
      <tbody>
       <% @users.each do |user| %>
       <tr>
        <td><%= attachment_image_tag user, :image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followings.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td><%= link_to "Show", user_path(user.id) %></td>
       </tr>
       <% end %>
      </tbody>
     </table>
   </div>
  </div>
</main>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Followings Users</h2>
<% if @users.exists? %>
<main>
  <p id="notice"></p>
  <div class='container px-3 px-sm-0'>
   <div class='row'>
     <table class='table'>
      <thead>
       <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
       </tr>
      </thead>
      <tbody>
       <% @users.each do |user| %>
       <tr>
        <td><%= attachment_image_tag user, :image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followings.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td><%= link_to "Show", user_path(user.id) %></td>
       </tr>
       <% end %>
      </tbody>
     </table>
   </div>
  </div>
</main>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/searches/_form.html.erb
<% if user_signed_in? %>
    <%= form_tag(search_path, method: :get) do %>
      <%= text_field_tag 'content' %>
      <%= select_tag 'model', options_for_select({ "User" => "user", "Book" => "book" }) %>
      <%= select_tag 'method', options_for_select({ "前後一致" => "forward", "後方一致" => "backward", "完全一致" => "perfect", "部分一致" => "partial" }) %>
      <%= submit_tag '検索' %>
    <% end %>
<% end %>

app/views/searches/search.html.erb
<% if @model == 'user' %>
  <h3>Users search for：<%= @content %></h3>
  <%= render 'users/users_index', users: @records %>
<% else @model == 'books' %>
  <h3>Books search for : <%= @content %></h3>
    <%= render 'books/index', books: @records %>
<% end %>

app/views/users/_post-count.html.erb
  <h1>投稿数の前日比・前週比</h1>
  <div class = "table_widht">
   <table class="table table-bordered">
    <thead>
     <th>今日の投稿数</th>
     <th>前日の投稿数</th>
     <th>前日比</th>
    </thead>
    <tbody>
     <tr>
      <td><%= @today_book.count %></td>
      <td><%= @yesterday_book.count %></td>
      <td>
       <% if @yesterday_book.count == 0 %>
         前日の投稿はありません
       <% else %>
         <% @the_day_before = @today_book.count / @yesterday_book.count.to_f %>
         <%= (@the_day_before * 100).round %>％
       <% end %>
      </td>
     </tr>
    </tbody>
   </table>
  </div>
  <div class = "table_widht">
   <table class="table table-bordered">
    <thead>
     <th>今週の投稿数</th>
     <th>前週の投稿数</th>
     <th>前週比</th>
    </thead>
    <tbody>
     <tr>
      <td><%= @this_week_book.count %></td>
      <td><%= @last_week_book.count %></td>
      <td>
       <% if @last_week_book.count == 0 %>
         前週の投稿はありません
       <% else %>
         <% @the_week_before = @this_week_book.count / @last_week_book.count.to_f %>
         <%= (@the_week_before * 100).round %>％
       <% end %>
      </td>
     </tr>
    </tbody>
   </table>
  </div>

app/views/users/_users_index.html.erb
<main>
  <p id="notice"></p>
  <div class='container px-3 px-sm-0'>
   <div class='row'>
     <table class='table'>
        <thead>
            <tr>
                <th></th>
                <th>Name</th>
                <th>Introduction</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody id="post">
        <% users.each do |user| %>
         <tr>
          <td><%= attachment_image_tag user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %></td>
          <td>
            <%= link_to user_path(user.id) do %>
             <%= user.name %>
            <% end %>
          </td>
          <td><%= user.introduction %></td>
         </tr>
        <% end %>
        </tbody>
     </table>
   </div>
  </div>
</main>

app/views/users/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <div id="error_explination">
          <% if @user.errors.any? %>
            <h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
            <% @user.errors.full_messages.each do |message| %>
              <ul>
               <li><%= message %></li>
              </ul>
            <% end %>
          <% end %>
        </div>
        <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name", class:"form-control" %>
        </div>
        <div class="form-group">
          <label for="user_image">Image</label>
          <%= f.attachment_field :profile_image, placegolder:"Image", class:"form-control-file user_image" %>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"Introduction", class:"form-control" %>
        </div>
          <%= f.submit "Update User" %>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
 <main>
  <p id="notice"></p>
  <div class='container px-5 px-sm-0'>
   <div class='row'>
    <%= render 'books/list', book: @books, user: @user %>
    <div class='col-md-8 offset-md-1'>
     <h2>Users</h2>
     <table class='table'>
      <thead>
       <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
       </tr>
      </thead>
      <tbody>
       <% @users.each do |user| %>
       <tr>
        <td><%= attachment_image_tag user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followings.count %>人</td>
        <td>フォロワー数：<%= user.followers.count %>人</td>
        <% if user.id != current_user.id %>
          <td class="button<%= user.id %>">
           <%= render "relationships/button", user: user %>
          </td>
        <% end %>
        <td><%= link_to "Show", user_path(user.id) %></td>
       </tr>
       <% end %>
      </tbody>
     </table>
    </div>
   </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <p id="notice"></p>
  <div class='container px-5 px-sm-0'>
   <div class='row'>
    <%= render 'books/list', book: @book, user: @user %>
    <div class='col-md-8 offset-md-1'>
     <h2>Books</h2>
     <table class="table table-hover table-inverse">
      <thead>
       <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
       </tr>
      </thead>
      <tbody>
       <% @books.each do |book| %>
       <tr>
        <td>
         <%= link_to user_path(book.user.id) do %>
          <%= attachment_image_tag book.user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
         <% end %>
        </td>
        <td><%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
        <td>コメント数：<%= book.post_comments.count %></td>
       </tr>
       <% end %>
      </tbody>
     </table>
     <%= render 'users/post-count', book: @book, user: @user %>
    </div>
   </div>
  </div>
</main>